import Ember from 'ember';
import EmberValidations from 'ember-validations';

export default Ember.ObjectController.extend(EmberValidations.Mixin,{
	countryOptions: [
		{id: "AF", name: "Afghanistan"},
		{id: "AX", name: "Åland Islands"},
		{id: "AL", name: "Albania"},
		{id: "DZ", name: "Algeria"},
		{id: "AS", name: "American Samoa"},
		{id: "AD", name: "Andorra"},
		{id: "AO", name: "Angola"},
		{id: "AI", name: "Anguilla"},
		{id: "AQ", name: "Antarctica"},
		{id: "AG", name: "Antigua and Barbuda"},
		{id: "AR", name: "Argentina"},
		{id: "AM", name: "Armenia"},
		{id: "AW", name: "Aruba"},
		{id: "AU", name: "Australia"},
		{id: "AT", name: "Austria"},
		{id: "AZ", name: "Azerbaijan"},
		{id: "BS", name: "Bahamas"},
		{id: "BH", name: "Bahrain"},
		{id: "BD", name: "Bangladesh"},
		{id: "BB", name: "Barbados"},
		{id: "BY", name: "Belarus"},
		{id: "BE", name: "Belgium"},
		{id: "BZ", name: "Belize"},
		{id: "BJ", name: "Benin"},
		{id: "BM", name: "Bermuda"},
		{id: "BT", name: "Bhutan"},
		{id: "BO", name: "Bolivia, Plurinational State of"},
		{id: "BQ", name: "Bonaire, Sint Eustatius and Saba"},
		{id: "BA", name: "Bosnia and Herzegovina"},
		{id: "BW", name: "Botswana"},
		{id: "BV", name: "Bouvet Island"},
		{id: "BR", name: "Brazil"},
		{id: "IO", name: "British Indian Ocean Territory"},
		{id: "BN", name: "Brunei Darussalam"},
		{id: "BG", name: "Bulgaria"},
		{id: "BF", name: "Burkina Faso"},
		{id: "BI", name: "Burundi"},
		{id: "KH", name: "Cambodia"},
		{id: "CM", name: "Cameroon"},
		{id: "CA", name: "Canada"},
		{id: "CV", name: "Cape Verde"},
		{id: "KY", name: "Cayman Islands"},
		{id: "CF", name: "Central African Republic"},
		{id: "TD", name: "Chad"},
		{id: "CL", name: "Chile"},
		{id: "CN", name: "China"},
		{id: "CX", name: "Christmas Island"},
		{id: "CC", name: "Cocos (Keeling) Islands"},
		{id: "CO", name: "Colombia"},
		{id: "KM", name: "Comoros"},
		{id: "CG", name: "Congo"},
		{id: "CD", name: "Congo, the Democratic Republic of the"},
		{id: "CK", name: "Cook Islands"},
		{id: "CR", name: "Costa Rica"},
		{id: "CI", name: "Côte d'Ivoire"},
		{id: "HR", name: "Croatia"},
		{id: "CU", name: "Cuba"},
		{id: "CW", name: "Curaçao"},
		{id: "CY", name: "Cyprus"},
		{id: "CZ", name: "Czech Republic"},
		{id: "DK", name: "Denmark"},
		{id: "DJ", name: "Djibouti"},
		{id: "DM", name: "Dominica"},
		{id: "DO", name: "Dominican Republic"},
		{id: "EC", name: "Ecuador"},
		{id: "EG", name: "Egypt"},
		{id: "SV", name: "El Salvador"},
		{id: "GQ", name: "Equatorial Guinea"},
		{id: "ER", name: "Eritrea"},
		{id: "EE", name: "Estonia"},
		{id: "ET", name: "Ethiopia"},
		{id: "FK", name: "Falkland Islands (Malvinas)"},
		{id: "FO", name: "Faroe Islands"},
		{id: "FJ", name: "Fiji"},
		{id: "FI", name: "Finland"},
		{id: "FR", name: "France"},
		{id: "GF", name: "French Guiana"},
		{id: "PF", name: "French Polynesia"},
		{id: "TF", name: "French Southern Territories"},
		{id: "GA", name: "Gabon"},
		{id: "GM", name: "Gambia"},
		{id: "GE", name: "Georgia"},
		{id: "DE", name: "Germany"},
		{id: "GH", name: "Ghana"},
		{id: "GI", name: "Gibraltar"},
		{id: "GR", name: "Greece"},
		{id: "GL", name: "Greenland"},
		{id: "GD", name: "Grenada"},
		{id: "GP", name: "Guadeloupe"},
		{id: "GU", name: "Guam"},
		{id: "GT", name: "Guatemala"},
		{id: "GG", name: "Guernsey"},
		{id: "GN", name: "Guinea"},
		{id: "GW", name: "Guinea-Bissau"},
		{id: "GY", name: "Guyana"},
		{id: "HT", name: "Haiti"},
		{id: "HM", name: "Heard Island and McDonald Islands"},
		{id: "VA", name: "Holy See (Vatican City State)"},
		{id: "HN", name: "Honduras"},
		{id: "HK", name: "Hong Kong"},
		{id: "HU", name: "Hungary"},
		{id: "IS", name: "Iceland"},
		{id: "IN", name: "India"},
		{id: "ID", name: "Indonesia"},
		{id: "IR", name: "Iran, Islamic Republic of"},
		{id: "IQ", name: "Iraq"},
		{id: "IE", name: "Ireland"},
		{id: "IM", name: "Isle of Man"},
		{id: "IL", name: "Israel"},
		{id: "IT", name: "Italy"},
		{id: "JM", name: "Jamaica"},
		{id: "JP", name: "Japan"},
		{id: "JE", name: "Jersey"},
		{id: "JO", name: "Jordan"},
		{id: "KZ", name: "Kazakhstan"},
		{id: "KE", name: "Kenya"},
		{id: "KI", name: "Kiribati"},
		{id: "KP", name: "Korea, Democratic People's Republic of"},
		{id: "KR", name: "Korea, Republic of"},
		{id: "KW", name: "Kuwait"},
		{id: "KG", name: "Kyrgyzstan"},
		{id: "LA", name: "Lao People's Democratic Republic"},
		{id: "LV", name: "Latvia"},
		{id: "LB", name: "Lebanon"},
		{id: "LS", name: "Lesotho"},
		{id: "LR", name: "Liberia"},
		{id: "LY", name: "Libya"},
		{id: "LI", name: "Liechtenstein"},
		{id: "LT", name: "Lithuania"},
		{id: "LU", name: "Luxembourg"},
		{id: "MO", name: "Macao"},
		{id: "MK", name: "Macedonia, the former Yugoslav Republic of"},
		{id: "MG", name: "Madagascar"},
		{id: "MW", name: "Malawi"},
		{id: "MY", name: "Malaysia"},
		{id: "MV", name: "Maldives"},
		{id: "ML", name: "Mali"},
		{id: "MT", name: "Malta"},
		{id: "MH", name: "Marshall Islands"},
		{id: "MQ", name: "Martinique"},
		{id: "MR", name: "Mauritania"},
		{id: "MU", name: "Mauritius"},
		{id: "YT", name: "Mayotte"},
		{id: "MX", name: "Mexico"},
		{id: "FM", name: "Micronesia, Federated States of"},
		{id: "MD", name: "Moldova, Republic of"},
		{id: "MC", name: "Monaco"},
		{id: "MN", name: "Mongolia"},
		{id: "ME", name: "Montenegro"},
		{id: "MS", name: "Montserrat"},
		{id: "MA", name: "Morocco"},
		{id: "MZ", name: "Mozambique"},
		{id: "MM", name: "Myanmar"},
		{id: "NA", name: "Namibia"},
		{id: "NR", name: "Nauru"},
		{id: "NP", name: "Nepal"},
		{id: "NL", name: "Netherlands"},
		{id: "NC", name: "New Caledonia"},
		{id: "NZ", name: "New Zealand"},
		{id: "NI", name: "Nicaragua"},
		{id: "NE", name: "Niger"},
		{id: "NG", name: "Nigeria"},
		{id: "NU", name: "Niue"},
		{id: "NF", name: "Norfolk Island"},
		{id: "MP", name: "Northern Mariana Islands"},
		{id: "NO", name: "Norway"},
		{id: "OM", name: "Oman"},
		{id: "PK", name: "Pakistan"},
		{id: "PW", name: "Palau"},
		{id: "PS", name: "Palestinian Territory, Occupied"},
		{id: "PA", name: "Panama"},
		{id: "PG", name: "Papua New Guinea"},
		{id: "PY", name: "Paraguay"},
		{id: "PE", name: "Peru"},
		{id: "PH", name: "Philippines"},
		{id: "PN", name: "Pitcairn"},
		{id: "PL", name: "Poland"},
		{id: "PT", name: "Portugal"},
		{id: "PR", name: "Puerto Rico"},
		{id: "QA", name: "Qatar"},
		{id: "RE", name: "Réunion"},
		{id: "RO", name: "Romania"},
		{id: "RU", name: "Russian Federation"},
		{id: "RW", name: "Rwanda"},
		{id: "BL", name: "Saint Barthélemy"},
		{id: "SH", name: "Saint Helena, Ascension and Tristan da Cunha"},
		{id: "KN", name: "Saint Kitts and Nevis"},
		{id: "LC", name: "Saint Lucia"},
		{id: "MF", name: "Saint Martin (French part)"},
		{id: "PM", name: "Saint Pierre and Miquelon"},
		{id: "VC", name: "Saint Vincent and the Grenadines"},
		{id: "WS", name: "Samoa"},
		{id: "SM", name: "San Marino"},
		{id: "ST", name: "Sao Tome and Principe"},
		{id: "SA", name: "Saudi Arabia"},
		{id: "SN", name: "Senegal"},
		{id: "RS", name: "Serbia"},
		{id: "SC", name: "Seychelles"},
		{id: "SL", name: "Sierra Leone"},
		{id: "SG", name: "Singapore"},
		{id: "SX", name: "Sint Maarten (Dutch part)"},
		{id: "SK", name: "Slovakia"},
		{id: "SI", name: "Slovenia"},
		{id: "SB", name: "Solomon Islands"},
		{id: "SO", name: "Somalia"},
		{id: "ZA", name: "South Africa"},
		{id: "GS", name: "South Georgia and the South Sandwich Islands"},
		{id: "SS", name: "South Sudan"},
		{id: "ES", name: "Spain"},
		{id: "LK", name: "Sri Lanka"},
		{id: "SD", name: "Sudan"},
		{id: "SR", name: "Suriname"},
		{id: "SJ", name: "Svalbard and Jan Mayen"},
		{id: "SZ", name: "Swaziland"},
		{id: "SE", name: "Sweden"},
		{id: "CH", name: "Switzerland"},
		{id: "SY", name: "Syrian Arab Republic"},
		{id: "TW", name: "Taiwan, Province of China"},
		{id: "TJ", name: "Tajikistan"},
		{id: "TZ", name: "Tanzania, United Republic of"},
		{id: "TH", name: "Thailand"},
		{id: "TL", name: "Timor-Leste"},
		{id: "TG", name: "Togo"},
		{id: "TK", name: "Tokelau"},
		{id: "TO", name: "Tonga"},
		{id: "TT", name: "Trinidad and Tobago"},
		{id: "TN", name: "Tunisia"},
		{id: "TR", name: "Turkey"},
		{id: "TM", name: "Turkmenistan"},
		{id: "TC", name: "Turks and Caicos Islands"},
		{id: "TV", name: "Tuvalu"},
		{id: "UG", name: "Uganda"},
		{id: "UA", name: "Ukraine"},
		{id: "AE", name: "United Arab Emirates"},
		{id: "GB", name: "United Kingdom"},
		{id: "US", name: "United States"},
		{id: "UM", name: "United States Minor Outlying Islands"},
		{id: "UY", name: "Uruguay"},
		{id: "UZ", name: "Uzbekistan"},
		{id: "VU", name: "Vanuatu"},
		{id: "VE", name: "Venezuela, Bolivarian Republic of"},
		{id: "VN", name: "Viet Nam"},
		{id: "VG", name: "Virgin Islands, British"},
		{id: "VI", name: "Virgin Islands, U.S."},
		{id: "WF", name: "Wallis and Futuna"},
		{id: "EH", name: "Western Sahara"},
		{id: "YE", name: "Yemen"},
		{id: "ZM", name: "Zambia"},
		{id: "ZW", name: "Zimbabwe"}
	], 

	selectedObject: null,

	flagClass: function() {
		var selectedObject = this.get("selectedObject.id") || "";
		return "flag-icon-" + selectedObject.toLowerCase();
	}.property('selectedObject'),

	isValid: Ember.computed(
		'model.title',
		'model.country',
		function() {
			return !Ember.isEmpty(this.get('model.title')) && !Ember.isEmpty(this.get('model.country'));
		}
	),
	actions: {
		save: function() {
			if (this.get('isValid')) {
				var _this = this;
				this.get('model').save().then(function(pyp) {
					_this.transitionToRoute('policy', pyp);
				});
			} else {
				this.set('errorMessage', 'You have to at least specify a title and a country.')
			}
			return false;
			},
		cancel: function() {
			this.transitionToRoute('policy', this.get('model'));
			return false;
		}
	},

	typologyOptions: [
		"Policy",
		"Program",
		"Strategy",
		"Policy Framework",
		"Other"
	],
	rFrameworkOptions: [
		"Law",
		"Decree",
		"Constitutional Article",
		"Other"
	],
	gCoverageOptions: [
		"Nat",
		"Dep",
		"Prov",
		"Com",
		"Other"
	],

	currencyOptions:[
		{id:"AED",	name:"AED - United Arab Emirates Dirham"},
		{id:"AFN",	name:"AFN - Afghanistan Afghani"},
		{id:"ALL",	name:"ALL - Albania Lek"},
		{id:"AMD",	name:"AMD - Armenia Dram"},
		{id:"ANG",	name:"ANG - Netherlands Antilles Guilder"},
		{id:"AOA",	name:"AOA - Angola Kwanza"},
		{id:"ARS",	name:"ARS - Argentina Peso"},
		{id:"AUD",	name:"AUD - Australia Dollar"},
		{id:"AWG",	name:"AWG - Aruba Guilder"},
		{id:"AZN",	name:"AZN - Azerbaijan New Manat"},
		{id:"BAM",	name:"BAM - Bosnia and Herzegovina Convertible Marka"},
		{id:"BBD",	name:"BBD - Barbados Dollar"},
		{id:"BDT",	name:"BDT - Bangladesh Taka"},
		{id:"BGN",	name:"BGN - Bulgaria Lev"},
		{id:"BHD",	name:"BHD - Bahrain Dinar"},
		{id:"BIF",	name:"BIF - Burundi Franc"},
		{id:"BMD",	name:"BMD - Bermuda Dollar"},
		{id:"BND",	name:"BND - Brunei Darussalam Dollar"},
		{id:"BOB",	name:"BOB - Bolivia Boliviano"},
		{id:"BRL",	name:"BRL - Brazil Real"},
		{id:"BSD",	name:"BSD - Bahamas Dollar"},
		{id:"BTN",	name:"BTN - Bhutan Ngultrum"},
		{id:"BWP",	name:"BWP - Botswana Pula"},
		{id:"BYR",	name:"BYR - Belarus Ruble"},
		{id:"BZD",	name:"BZD - Belize Dollar"},
		{id:"CAD",	name:"CAD - Canada Dollar"},
		{id:"CDF",	name:"CDF - Congo/Kinshasa Franc"},
		{id:"CHF",	name:"CHF - Switzerland Franc"},
		{id:"CLP",	name:"CLP - Chile Peso"},
		{id:"CNY",	name:"CNY - China Yuan Renminbi"},
		{id:"COP",	name:"COP - Colombia Peso"},
		{id:"CRC",	name:"CRC - Costa Rica Colon"},
		{id:"CUC",	name:"CUC - Cuba Convertible Peso"},
		{id:"CUP",	name:"CUP - Cuba Peso"},
		{id:"CVE",	name:"CVE - Cape Verde Escudo"},
		{id:"CZK",	name:"CZK - Czech Republic Koruna"},
		{id:"DJF",	name:"DJF - Djibouti Franc"},
		{id:"DKK",	name:"DKK - Denmark Krone"},
		{id:"DOP",	name:"DOP - Dominican Republic Peso"},
		{id:"DZD",	name:"DZD - Algeria Dinar"},
		{id:"EGP",	name:"EGP - Egypt Pound"},
		{id:"ERN",	name:"ERN - Eritrea Nakfa"},
		{id:"ETB",	name:"ETB - Ethiopia Birr"},
		{id:"EUR",	name:"EUR - Euro Member Countries"},
		{id:"FJD",	name:"FJD - Fiji Dollar"},
		{id:"FKP",	name:"FKP - Falkland Islands (Malvinas) Pound"},
		{id:"GBP",	name:"GBP - United Kingdom Pound"},
		{id:"GEL",	name:"GEL - Georgia Lari"},
		{id:"GGP",	name:"GGP - Guernsey Pound"},
		{id:"GHS",	name:"GHS - Ghana Cedi"},
		{id:"GIP",	name:"GIP - Gibraltar Pound"},
		{id:"GMD",	name:"GMD - Gambia Dalasi"},
		{id:"GNF",	name:"GNF - Guinea Franc"},
		{id:"GTQ",	name:"GTQ - Guatemala Quetzal"},
		{id:"GYD",	name:"GYD - Guyana Dollar"},
		{id:"HKD",	name:"HKD - Hong Kong Dollar"},
		{id:"HNL",	name:"HNL - Honduras Lempira"},
		{id:"HRK",	name:"HRK - Croatia Kuna"},
		{id:"HTG",	name:"HTG - Haiti Gourde"},
		{id:"HUF",	name:"HUF - Hungary Forint"},
		{id:"IDR",	name:"IDR - Indonesia Rupiah"},
		{id:"ILS",	name:"ILS - Israel Shekel"},
		{id:"IMP",	name:"IMP - Isle of Man Pound"},
		{id:"INR",	name:"INR - India Rupee"},
		{id:"IQD",	name:"IQD - Iraq Dinar"},
		{id:"IRR",	name:"IRR - Iran Rial"},
		{id:"ISK",	name:"ISK - Iceland Krona"},
		{id:"JEP",	name:"JEP - Jersey Pound"},
		{id:"JMD",	name:"JMD - Jamaica Dollar"},
		{id:"JOD",	name:"JOD - Jordan Dinar"},
		{id:"JPY",	name:"JPY - Japan Yen"},
		{id:"KES",	name:"KES - Kenya Shilling"},
		{id:"KGS",	name:"KGS - Kyrgyzstan Som"},
		{id:"KHR",	name:"KHR - Cambodia Riel"},
		{id:"KMF",	name:"KMF - Comoros Franc"},
		{id:"KPW",	name:"KPW - Korea (North) Won"},
		{id:"KRW",	name:"KRW - Korea (South) Won"},
		{id:"KWD",	name:"KWD - Kuwait Dinar"},
		{id:"KYD",	name:"KYD - Cayman Islands Dollar"},
		{id:"KZT",	name:"KZT - Kazakhstan Tenge"},
		{id:"LAK",	name:"LAK - Laos Kip"},
		{id:"LBP",	name:"LBP - Lebanon Pound"},
		{id:"LKR",	name:"LKR - Sri Lanka Rupee"},
		{id:"LRD",	name:"LRD - Liberia Dollar"},
		{id:"LSL",	name:"LSL - Lesotho Loti"},
		{id:"LYD",	name:"LYD - Libya Dinar"},
		{id:"MAD",	name:"MAD - Morocco Dirham"},
		{id:"MDL",	name:"MDL - Moldova Leu"},
		{id:"MGA",	name:"MGA - Madagascar Ariary"},
		{id:"MKD",	name:"MKD - Macedonia Denar"},
		{id:"MMK",	name:"MMK - Myanmar (Burma) Kyat"},
		{id:"MNT",	name:"MNT - Mongolia Tughrik"},
		{id:"MOP",	name:"MOP - Macau Pataca"},
		{id:"MRO",	name:"MRO - Mauritania Ouguiya"},
		{id:"MUR",	name:"MUR - Mauritius Rupee"},
		{id:"MVR",	name:"MVR - Maldives (Maldive Islands) Rufiyaa"},
		{id:"MWK",	name:"MWK - Malawi Kwacha"},
		{id:"MXN",	name:"MXN - Mexico Peso"},
		{id:"MYR",	name:"MYR - Malaysia Ringgit"},
		{id:"MZN",	name:"MZN - Mozambique Metical"},
		{id:"NAD",	name:"NAD - Namibia Dollar"},
		{id:"NGN",	name:"NGN - Nigeria Naira"},
		{id:"NIO",	name:"NIO - Nicaragua Cordoba"},
		{id:"NOK",	name:"NOK - Norway Krone"},
		{id:"NPR",	name:"NPR - Nepal Rupee"},
		{id:"NZD",	name:"NZD - New Zealand Dollar"},
		{id:"OMR",	name:"OMR - Oman Rial"},
		{id:"PAB",	name:"PAB - Panama Balboa"},
		{id:"PEN",	name:"PEN - Peru Nuevo Sol"},
		{id:"PGK",	name:"PGK - Papua New Guinea Kina"},
		{id:"PHP",	name:"PHP - Philippines Peso"},
		{id:"PKR",	name:"PKR - Pakistan Rupee"},
		{id:"PLN",	name:"PLN - Poland Zloty"},
		{id:"PYG",	name:"PYG - Paraguay Guarani"},
		{id:"QAR",	name:"QAR - Qatar Riyal"},
		{id:"RON",	name:"RON - Romania New Leu"},
		{id:"RSD",	name:"RSD - Serbia Dinar"},
		{id:"RUB",	name:"RUB - Russia Ruble"},
		{id:"RWF",	name:"RWF - Rwanda Franc"},
		{id:"SAR",	name:"SAR - Saudi Arabia Riyal"},
		{id:"SBD",	name:"SBD - Solomon Islands Dollar"},
		{id:"SCR",	name:"SCR - Seychelles Rupee"},
		{id:"SDG",	name:"SDG - Sudan Pound"},
		{id:"SEK",	name:"SEK - Sweden Krona"},
		{id:"SGD",	name:"SGD - Singapore Dollar"},
		{id:"SHP",	name:"SHP - Saint Helena Pound"},
		{id:"SLL",	name:"SLL - Sierra Leone Leone"},
		{id:"SOS",	name:"SOS - Somalia Shilling"},
		{id:"SPL",  name:"SPL - Seborga Luigino"},
		{id:"SRD",	name:"SRD - Suriname Dollar"},
		{id:"STD",	name:"STD - São Tomé and Príncipe Dobra"},
		{id:"SVC",	name:"SVC - El Salvador Colon"},
		{id:"SYP",	name:"SYP - Syria Pound"},
		{id:"SZL",	name:"SZL - Swaziland Lilangeni"},
		{id:"THB",	name:"THB - Thailand Baht"},
		{id:"TJS",	name:"TJS - Tajikistan Somoni"},
		{id:"TMT",	name:"TMT - Turkmenistan Manat"},
		{id:"TND",	name:"TND - Tunisia Dinar"},
		{id:"TOP",	name:"TOP - Tonga Pa'anga"},
		{id:"TRY",	name:"TRY - Turkey Lira"},
		{id:"TTD",	name:"TTD - Trinidad and Tobago Dollar"},
		{id:"TVD",	name:"TVD - Tuvalu Dollar"},
		{id:"TWD",	name:"TWD - Taiwan New Dollar"},
		{id:"TZS",	name:"TZS - Tanzania Shilling"},
		{id:"UAH",	name:"UAH - Ukraine Hryvnia"},
		{id:"UGX",	name:"UGX - Uganda Shilling"},
		{id:"USD",	name:"USD - United States Dollar"},
		{id:"UYU",	name:"UYU - Uruguay Peso"},
		{id:"UZS",	name:"UZS - Uzbekistan Som"},
		{id:"VEF",	name:"VEF - Venezuela Bolivar"},
		{id:"VND",	name:"VND - Viet Nam Dong"},
		{id:"VUV",	name:"VUV - Vanuatu Vatu"},
		{id:"WST",	name:"WST - Samoa Tala"},
		{id:"XAF",	name:"XAF - Communauté Financière Africaine (BEAC) CFA Franc BEAC"},
		{id:"XCD",	name:"XCD - East Caribbean Dollar"},
		{id:"XDR",	name:"XDR - International Monetary Fund (IMF) Special Drawing Rights"},
		{id:"XOF",	name:"XOF - Communauté Financière Africaine (BCEAO) Franc"},
		{id:"XPF",	name:"XPF - Comptoirs Français du Pacifique (CFP) Franc"},
		{id:"YER",	name:"YER - Yemen Rial"},
		{id:"ZAR",	name:"ZAR - South Africa Rand"},
		{id:"ZMW",	name:"ZMW - Zambia Kwacha"},
		{id:"ZWD",	name:"ZWD - Zimbabwe Dollar"}
	]
});
